# File config.physical.py Created by Lucius Schoenbaum October 20, 2025

"""
The following dict of dicts define a reasonable set of defaults
for particular trajectory/background/diffusion types.
These defaults are intended to be more useful
than the fallthrough defaults. This information makes this script
the location in the code where these default values are maintained.

To aid both the maintainer/developer and user,
only the *relevant* parameters are included
in each list. The maintainer/developer can therefore
focus on a particular class whose default values are being intelligently
chosen based on physics and numerics. Meanwhile, the
lists and dicts in `config.py` are more software-oriented,
and less physics-oriented.
"""


physical_defaults = {
    'background':{
        'CylindricalObstacle': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'Dipole': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'Discontinuity': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'MagnetizedCylinder': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'MagnetizedSphere': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'Server': {
            'derivative_method': 'numeric',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'server_num_ghost_cells': 2,
            'server_interpolation_order': 1,
        },
        'ServerBATL': {
            'derivative_method': 'numeric',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'server_num_ghost_cells': 2,
            'server_interpolation_order': 1,
        },
        'ServerCartesian': {
            'derivative_method': 'numeric',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'server_num_ghost_cells': 2,
            'server_interpolation_order': 1,
        },
        'Shock': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'SmoothDiscontinuity': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'smooth_discontinuity_order': 4,
        },
        'SmoothShock': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'smooth_discontinuity_order': 4,
        },
        'SolarWind': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
            'solarwind_current_sheet': 'disabled',
            'solarwind_sectored_region': 'nowhere',
            'solarwind_polar_correction': 'none',
            'solarwind_speed_latitude_profile': 'constant',
            'solarwind_termshock_speed_exponent': 'square',
        },
        'SolarWindTermShock': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'SphericalObstacle': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'Uniform': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'VLISMBochum': {
            'derivative_method': 'numeric',
            'mod_type': 'scaled',
            'mod_rpos': 'scale_rel_zero',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
        'Waves': {
            'derivative_method': 'analytic',
            'num_numeric_grad_evals': 1,
            'incr_dmax_ratio': 0.0001,
        },
    },
    'trajectory': {
        'Fieldline': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
        },
        'Focused': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'use_B_drifts': "none",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
        },
        'Guiding': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
        },
        'GuidingDiff': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
        },
        'GuidingScatt': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
            'split_scatt_fraction': 0.0,
            'const_dmumax': "constant_dtheta_max",
            'stochastic_method': "Euler",
            'cfl_pitchangle': 0.5,
        },
        'GuidingDiffScatt': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
            'split_scatt_fraction': 0.0,
            'const_dmumax': "constant_dtheta_max",
            'stochastic_method_mu': "Euler",
            'stochastic_method_perp': "Euler",
            'cfl_pitchangle': 0.5,
        },
        'Lorentz': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.1,
            'drift_safety': 0.5,
            'mirror_threshold': 300,
            'steps_per_orbit': 100,
        },
        'Parker': {
            'time_flow': 'forward',
            'rk_integrator': "DormandPrince_54E",
            'record_mag_extrema': False,
            'record_trajectory': False,
            'record_trajectory_segment_presize': 10000,
            'advance_safety_level': 'low',
            'max_trajectory_steps': 100000,
            'max_time_adaptations': 1,
            'n_max_calls': -1,
            ####
            'pperp_method': "scheme",
            'cfl_advection': 0.5,
            'drift_safety': 0.5,
            'mirror_threshold': 10,
            'stochastic_method': "Euler",
            'use_B_drifts': "none",
            'divk_method': "direct",
            'cfl_diffusion': 0.5,
            'cfl_acceleration': 0.5,
            'dlnp_max': 0.01,
        },
    },
    'diffusion': {
        'None': {
        },
        'IsotropicConstant': {
            'D0': 1.0,
        },
        'ParaConstant': {
            'D0': 1.0,
        },
        'PerpConstant': {
            'D0': 1.0,
        },
        'FullConstant': {
            'Dperp': 1.0,
            'Dpara': 1.0,
        },
        'QLTConstant': {
            'A2A': 1.0,
            'l_max': 1.0,
            'k_min': 1.0,
            'ps_index': 1.0,
            'ps_minus': 1.0,
        },
        'WNLTConstant': {
            'use_qlt_scatt': False,
            'A2A': 1.0,
            'l_max': 1.0,
            'k_min': 1.0,
            'ps_index': 1.0,
            'ps_minus': 1.0,
            'A2T': 1.0,
            'A2L': 1.0,
            'ps_plus': 1.0,
        },
        'WNLTRampVLISM': {
            'use_qlt_scatt': False,
            'A2A': 1.0,
            'l_max': 1.0,
            'k_min': 1.0,
            'ps_index': 1.0,
            'ps_minus': 1.0,
            'A2T': 1.0,
            'A2L': 1.0,
            'ps_plus': 1.0,
            #
            'k_min_ref': 1.0,
            'A2A_ref': 1.0,
            'A2T_ref': 1.0,
            'A2L_ref': 1.0,
            'l_max_HP': 1.0,
            'dl_max': 1.0,
            'z_nose': 1.0,
            'z_sheath': 1.0,
            'nose_dz': 1.0,
        },
        'FlowMomentumPowerLaw': {
            'kappa0': 1.0,
            'U0': 1.0,
            'pow_law_U': 1.0,
            'p0': 1.0,
            'pow_law_p': 1.0,
            'kappa_ratio': 1.0,
        },
        'KineticEnergyRadialDistancePowerLaw': {
            'kappa0': 1.0,
            'T0': 1.0,
            'r0': 1.0,
            'pow_law_T': 1.0,
            'pow_law_r': 1.0,
            'kappa_ratio': 1.0,
            'stream_dep_idx': 1,
            'u_upstream': 1.0,
            'w_sh': 1.0,
            's_sh': 1.0,
            'dn_up_ratio': 1.0,
        },
        'RigidityMagneticFieldPowerLaw': {
            'lam0': 1.0,
            'R0': 1.0,
            'B0': 1.0,
            'pow_law_R': 1.0,
            'pow_law_B': 1.0,
            'kappa_ratio': 1.0,
        },
        'StraussEtAl2013': {
            'LISM_idx': 1,
            'lam_inner': 1.0,
            'lam_outer': 1.0,
            'R0': 1.0,
            'B0': 1.0,
            'kappa_ratio_inner': 1.0,
            'kappa_ratio_outer': 1.0,
        },
        'GuoEtAl2014': {
            # same as StraussEtAl2013
            'LISM_idx': 1,
            'lam_inner': 1.0,
            'lam_outer': 1.0,
            'R0': 1.0,
            'B0': 1.0,
            'kappa_ratio_inner': 1.0,
            'kappa_ratio_outer': 1.0,
        },
        'PotgieterEtAl2015': {
            'LISM_idx': 1,
            'kappa_inner': 1.0,
            'kappa_outer': 1.0,
            'R0': 1.0,
            'B0': 1.0,
            'kappa_ratio_inner': 1.0,
            'kappa_ratio_outer': 1.0,
        },
        'EmpiricalSOQLTandUNLT': {
            'lam_para': 1.0,
            'lam_perp': 1.0,
            'R0': 1.0,
            'B0': 1.0,
            'Bmix_idx': 1,
            'kappa_ratio_red': 1.0,
            'radial_limit_perp_red': 1.0,
            'solar_cycle_idx': 1,
            'solar_cycle_effect': 1.0,
        },
    },
}




