/*!
\file variable_lists.hh
\author Vladimir Florinski
\author Lucius Schoenbaum
\author Juan G Alonso Guzman

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
This file is automatically generated by generate.py. 
Do not edit this file, instead edit generate.py. 
*/

#ifndef SPECTRUM_VARIABLE_LISTS_HH
#define SPECTRUM_VARIABLE_LISTS_HH

#include <array>

namespace Spectrum {

/*!
Identifiers for distinguished code-wide variables (for lookup).
\author Lucius Schoenbaum
\date 03/25/2025
*/
enum VariableId {
anon,
Den,
FlxDen,
Prs,
Enr,
FlxEnr,
Vel,
Mom,
FlxMom,
Mag,
FlxMag,
Glm,
FlxGlm,
Elc,
AbsMag,
HatMag,
DelVel,
DelElc,
DelMag,
DelAbsMag,
DelHatMag,
DerVel,
DerElc,
DerMag,
DerAbsMag,
DerHatMag,
PrimitiveStateGASDYN,
ConservedStateGASDYN,
FluxFunctionGASDYN,
PrimitiveStateMHD,
ConservedStateMHD,
FluxFunctionMHD,
PrimitiveStateMHD_GLM,
ConservedStateMHD_GLM,
FluxFunctionMHD_GLM,
};

/*!
Formatted names for distinguished code-wide variables
(minimal formatting in ASCII).
\author Lucius Schoenbaum
\date 03/25/2025
*/
const constexpr std::array<std::string_view, 35> VariableNames = {
   std::string_view(""),
   std::string_view("Den"),
   std::string_view("FlxDen"),
   std::string_view("Prs"),
   std::string_view("Enr"),
   std::string_view("FlxEnr"),
   std::string_view("Vel"),
   std::string_view("Mom"),
   std::string_view("FlxMom"),
   std::string_view("Mag"),
   std::string_view("FlxMag"),
   std::string_view("Glm"),
   std::string_view("FlxGlm"),
   std::string_view("Elc"),
   std::string_view("AbsMag"),
   std::string_view("HatMag"),
   std::string_view("DelVel"),
   std::string_view("DelElc"),
   std::string_view("DelMag"),
   std::string_view("DelAbsMag"),
   std::string_view("DelHatMag"),
   std::string_view("DerVel"),
   std::string_view("DerElc"),
   std::string_view("DerMag"),
   std::string_view("DerAbsMag"),
   std::string_view("DerHatMag"),
   std::string_view("PrimitiveStateGASDYN"),
   std::string_view("ConservedStateGASDYN"),
   std::string_view("FluxFunctionGASDYN"),
   std::string_view("PrimitiveStateMHD"),
   std::string_view("ConservedStateMHD"),
   std::string_view("FluxFunctionMHD"),
   std::string_view("PrimitiveStateMHD_GLM"),
   std::string_view("ConservedStateMHD_GLM"),
   std::string_view("FluxFunctionMHD_GLM"),
};

// Note: more maps can be added (e.g. unit/scale factor)

}

#endif
