/*!
\file variable_groups.hh
\author Vladimir Florinski
\author Lucius Schoenbaum
\author Juan G Alonso Guzman

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
This file is automatically generated by generate.py. 
Do not edit this file, instead edit generate.py. 
*/

#ifndef SPECTRUM_VARIABLE_GROUPS_HH
#define SPECTRUM_VARIABLE_GROUPS_HH

#include "../mhdtuple/namedmhdtuple.hh"

namespace Spectrum {

/*!
\brief Variables of the primitive form for a gas dynamics model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using PrimitiveStateGASDYN_t = NamedMHDtuple<VariableId::PrimitiveStateGASDYN, Den_t, Vel_t, Prs_t>;

/*!
\brief Variables of the conserved form for a gas dynamics model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using ConservedStateGASDYN_t = NamedMHDtuple<VariableId::ConservedStateGASDYN, Den_t, Mom_t, Enr_t>;

/*!
\brief Variables of the flux function for a gas dynamics model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FluxFunctionGASDYN_t = NamedMHDtuple<VariableId::FluxFunctionGASDYN, FlxDen_t, FlxMom_t, FlxEnr_t>;

/*!
\brief Variables of the primitive form for an MHD model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using PrimitiveStateMHD_t = NamedMHDtuple<VariableId::PrimitiveStateMHD, Den_t, Vel_t, Prs_t, Mag_t>;

/*!
\brief Variables of the conserved form for an MHD model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using ConservedStateMHD_t = NamedMHDtuple<VariableId::ConservedStateMHD, Den_t, Mom_t, Enr_t, Mag_t>;

/*!
\brief Variables of the flux function for an MHD model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FluxFunctionMHD_t = NamedMHDtuple<VariableId::FluxFunctionMHD, FlxDen_t, FlxMom_t, FlxEnr_t, FlxMag_t>;

/*!
\brief Variables of the primitive form for an MHD-GLM model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using PrimitiveStateMHD_GLM_t = NamedMHDtuple<VariableId::PrimitiveStateMHD_GLM, Den_t, Vel_t, Prs_t, Mag_t, Glm_t>;

/*!
\brief Variables of the conserved form for an MHD-GLM model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using ConservedStateMHD_GLM_t = NamedMHDtuple<VariableId::ConservedStateMHD_GLM, Den_t, Mom_t, Enr_t, Mag_t, Glm_t>;

/*!
\brief Variables of the flux function for an MHD-GLM model type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FluxFunctionMHD_GLM_t = NamedMHDtuple<VariableId::FluxFunctionMHD_GLM, FlxDen_t, FlxMom_t, FlxEnr_t, FlxMag_t, FlxGlm_t>;

};

#endif
