/*!
\file variable_types.hh
\author Vladimir Florinski
\author Lucius Schoenbaum
\author Juan G Alonso Guzman

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
This file is automatically generated by generate.py. 
Do not edit this file, instead edit generate.py. 
*/

#ifndef SPECTRUM_VARIABLE_TYPES_HH
#define SPECTRUM_VARIABLE_TYPES_HH

#include "../variable_structs.hh"

namespace Spectrum {

/*!
\brief Fluid density field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Den_t = NamedScalar<VariableId::Den, 1, 1>;

/*!
\brief Fluid density flux function type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FlxDen_t = NamedScalar<VariableId::FlxDen, 1, 1>;

/*!
\brief Fluid pressure field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Prs_t = NamedScalar<VariableId::Prs, 1, 1>;

/*!
\brief Fluid energy field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Enr_t = NamedScalar<VariableId::Enr, 1, 1>;

/*!
\brief Fluid energy flux function type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FlxEnr_t = NamedScalar<VariableId::FlxEnr, 1, 0>;

/*!
\brief Fluid velocity field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Vel_t = NamedGeoVector<VariableId::Vel, 1, 0>;

/*!
\brief Fluid momentum field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Mom_t = NamedGeoVector<VariableId::Mom, 1, 0>;

/*!
\brief Fluid momentum flux function type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FlxMom_t = NamedGeoVector<VariableId::FlxMom, 1, 0>;

/*!
\brief Magnetic field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Mag_t = NamedGeoVector<VariableId::Mag, 1, 0>;

/*!
\brief Magnetic field flux function type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FlxMag_t = NamedGeoVector<VariableId::FlxMag, 1, 0>;

/*!
\brief Lagrange multiplier field of GLM MHD type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Glm_t = NamedScalar<VariableId::Glm, 1, 0>;

/*!
\brief Lagrange mutlipler flux function of GLM MHD type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using FlxGlm_t = NamedScalar<VariableId::FlxGlm, 1, 0>;

/*!
\brief Electric field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using Elc_t = NamedGeoVector<VariableId::Elc, 1, 0>;

/*!
\brief Magnetic field magnitude type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using AbsMag_t = NamedScalar<VariableId::AbsMag, 1, 0>;

/*!
\brief Magnetic field direction type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using HatMag_t = NamedGeoVector<VariableId::HatMag, 1, 0>;

/*!
\brief Gradient of velocity field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DelVel_t = NamedGeoMatrix<VariableId::DelVel, 1, 0>;

/*!
\brief Gradient of electric field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DelElc_t = NamedGeoMatrix<VariableId::DelElc, 1, 0>;

/*!
\brief Gradient of magnetic field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DelMag_t = NamedGeoMatrix<VariableId::DelMag, 1, 0>;

/*!
\brief Gradient of magnetic field magnitude type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DelAbsMag_t = NamedGeoVector<VariableId::DelAbsMag, 1, 0>;

/*!
\brief Gradient of magnetic field direction  type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DelHatMag_t = NamedGeoMatrix<VariableId::DelHatMag, 1, 0>;

/*!
\brief Time derivative of velocity field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DerVel_t = NamedGeoVector<VariableId::DerVel, 1, 0>;

/*!
\brief Time derivative of electric field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DerElc_t = NamedGeoVector<VariableId::DerElc, 1, 0>;

/*!
\brief Time derivative of magnetic field type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DerMag_t = NamedGeoVector<VariableId::DerMag, 1, 0>;

/*!
\brief Time derivative of magnetic field magnitude type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DerAbsMag_t = NamedScalar<VariableId::DerAbsMag, 1, 0>;

/*!
\brief Time derivative of magnetic field direction type with a formatted name
\author Lucius Schoenbaum
\date 03/25/2025
*/
using DerHatMag_t = NamedGeoVector<VariableId::DerHatMag, 1, 0>;

};

#endif
