/*!
\file namedmhdtuple.hh
\author Vladimir Florinski
\author Lucius Schoenbaum
\author Juan G Alonso Guzman

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
This file contains a block of code generated by generate.py.
Do not edit the contents of this file within the block bounded by
the pragmas "BEGIN(variables/generate)" and "END(variables/generate)",
instead edit the file `variables/generate.py`.
Elsewhere, this file can be edited normally.
*/

#ifndef SPECTRUM_NAMEDMHDTUPLE_HH
#define SPECTRUM_NAMEDMHDTUPLE_HH

#include <iostream>
#include <any>
#include <stdexcept>
#include "../generate/variable_types.hh"

namespace Spectrum {

/*!
\brief Multi-purpose class storing physical data defined at a spatial location.
Used in the data interface with the (pseudo-)particle tracer, and to house
data distributed on the grid.
\author Lucius Schoenbaum
\author Vladimir Florinski
\note Recursion in protected methods takes place only once, at compile time.
*/
template <VariableId nameid, typename T, typename ... Ts>
struct NamedMHDtuple: public NamedMHDtuple<nameid, Ts...> {

protected:

   T data;

/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] index index into tuple
\param[in] f universal reference function, typically rvalue lambda defined at time of call
\param[in] others variadic universal reference of other tuples having the same tuple type
\note Public access via visit()
*/
   template <typename Function>
   void visit_unpacked(std::size_t index, Function&& f, auto&&... others) {
      if (index == 0) {
         f(data, others.data...);
      } else {
         NamedMHDtuple<nameid, Ts...>::visit_unpacked(index - 1, std::forward<Function>(f), static_cast<NamedMHDtuple<nameid, Ts...>>(others)...);
      }
   }

/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] f universal reference function, typically rvalue lambda defined at time of call
\param[in] others variadic universal reference of other tuples having the same tuple type
\note Public access via foreach()
*/
   template <typename Function>
   void foreach_unpacked(Function&& f, auto&&... others) {
      f(data, others.data...);
      NamedMHDtuple<nameid, Ts...>::foreach_unpacked(std::forward<Function>(f), static_cast<NamedMHDtuple<nameid, Ts...>>(others)...);
   }
   
public:

   static constexpr const std::string_view name = VariableNames[nameid];

   NamedMHDtuple(void) = default;

   explicit NamedMHDtuple(T in, Ts... rest):
      NamedMHDtuple<nameid, Ts...>(rest...),
       data(in)
   {};


/*!
\author Lucius Schoenbaum
\author Vladimir Florinski
\date 07/02/2024
\param[in] other Structure to copy from
\return Reference to the object
*/
   NamedMHDtuple& operator=(const NamedMHDtuple& other) {
      NamedMHDtuple<nameid, Ts...>::operator=(other);
      data = other.data;
      return *this;
   };
  
/*!
\author Lucius Schoenbaum
\date 05/28/2025
\return size of tuple
*/
   size_t size() const {
      return sizeof...(Ts)+1;
   }
  
/*!
\author Lucius Schoenbaum
\date 05/28/2025
\return constant reference to top element of tuple
*/
   const T& top() const {
      return data;
   }

/*!
\author Lucius Schoenbaum
\date 05/28/2025
\return reference to top element of tuple
*/
   T& top() {
      return data;
   }

/*!
\author Lucius Schoenbaum
\date 05/28/2025
\param[in] index index into tuple
\return Reference to member of tuple evaluated at runtime
\note Type of return value must be known (and any_cast to) by caller. 
If this is not the case, use get<index>(mhdtuple).
*/
   std::any operator[](std::size_t index) const {
      if (index == 0)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::operator[](index-1);
   }

/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] index index into tuple
\param[in] f universal reference function, typically rvalue lambda defined at time of call
\param[in] others variadic universal reference of other tuples having the same tuple type
*/
   template <typename Function, typename Others>
   void visit(std::size_t i, Function&& f, Others&& others) {
      std::apply(
            [&](auto&&... others) {
               visit_unpacked(i, std::forward<Function>(f), std::forward<decltype(others)>(others)...);
            },
            std::forward<Others>(others)
      );
   }



/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] f universal reference function, typically rvalue lambda defined at time of call
\param[in] others variadic universal reference of other tuples having the same tuple type
*/
   template <typename Function, typename Others>
   void foreach(Function&& f, Others&& others) {
      std::apply(
            [&](auto&&... others) {
               foreach_unpacked(std::forward<Function>(f), std::forward<decltype(others)>(others)...);
            },
            std::forward<Others>(others)
      );
   }

/*!
\author Lucius Schoenbaum
\date 05/28/2025
\param[in] f Function to evaluate on each tuple member
\return Reference to the object
*/
   template <typename Function>
   void foreach(Function&& f) {
      f(data);
      NamedMHDtuple<nameid, Ts...>::foreach(f);
   }


   // BEGIN(variables/generate, class)

/*!
\brief Get den (Fluid density field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   denT& den(void) {
      if constexpr (std::is_same<T, denT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::den();
   };

/*!
\brief Get den (Fluid density field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const denT& den(void) const {
      if constexpr (std::is_same<T, denT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::den();
   };


/*!
\brief Whether den (Fluid density field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool den_found(void) {
      if constexpr (std::is_same<T, denT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::den_found();
   };
   

/*!
\brief Get fden (Fluid density flux function) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   fdenT& fden(void) {
      if constexpr (std::is_same<T, fdenT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fden();
   };

/*!
\brief Get fden (Fluid density flux function) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const fdenT& fden(void) const {
      if constexpr (std::is_same<T, fdenT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fden();
   };


/*!
\brief Whether fden (Fluid density flux function) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool fden_found(void) {
      if constexpr (std::is_same<T, fdenT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::fden_found();
   };
   

/*!
\brief Get prs (Fluid pressure field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   prsT& prs(void) {
      if constexpr (std::is_same<T, prsT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::prs();
   };

/*!
\brief Get prs (Fluid pressure field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const prsT& prs(void) const {
      if constexpr (std::is_same<T, prsT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::prs();
   };


/*!
\brief Whether prs (Fluid pressure field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool prs_found(void) {
      if constexpr (std::is_same<T, prsT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::prs_found();
   };
   

/*!
\brief Get enr (Fluid energy field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   enrT& enr(void) {
      if constexpr (std::is_same<T, enrT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::enr();
   };

/*!
\brief Get enr (Fluid energy field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const enrT& enr(void) const {
      if constexpr (std::is_same<T, enrT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::enr();
   };


/*!
\brief Whether enr (Fluid energy field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool enr_found(void) {
      if constexpr (std::is_same<T, enrT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::enr_found();
   };
   

/*!
\brief Get fenr (Fluid energy flux function) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   fenrT& fenr(void) {
      if constexpr (std::is_same<T, fenrT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fenr();
   };

/*!
\brief Get fenr (Fluid energy flux function) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const fenrT& fenr(void) const {
      if constexpr (std::is_same<T, fenrT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fenr();
   };


/*!
\brief Whether fenr (Fluid energy flux function) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool fenr_found(void) {
      if constexpr (std::is_same<T, fenrT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::fenr_found();
   };
   

/*!
\brief Get vel (Fluid velocity field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   velT& vel(void) {
      if constexpr (std::is_same<T, velT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::vel();
   };

/*!
\brief Get vel (Fluid velocity field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const velT& vel(void) const {
      if constexpr (std::is_same<T, velT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::vel();
   };


/*!
\brief Whether vel (Fluid velocity field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool vel_found(void) {
      if constexpr (std::is_same<T, velT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::vel_found();
   };
   

/*!
\brief Get mom (Fluid momentum field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   momT& mom(void) {
      if constexpr (std::is_same<T, momT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::mom();
   };

/*!
\brief Get mom (Fluid momentum field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const momT& mom(void) const {
      if constexpr (std::is_same<T, momT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::mom();
   };


/*!
\brief Whether mom (Fluid momentum field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool mom_found(void) {
      if constexpr (std::is_same<T, momT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::mom_found();
   };
   

/*!
\brief Get fmom (Fluid momentum flux function) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   fmomT& fmom(void) {
      if constexpr (std::is_same<T, fmomT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fmom();
   };

/*!
\brief Get fmom (Fluid momentum flux function) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const fmomT& fmom(void) const {
      if constexpr (std::is_same<T, fmomT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fmom();
   };


/*!
\brief Whether fmom (Fluid momentum flux function) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool fmom_found(void) {
      if constexpr (std::is_same<T, fmomT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::fmom_found();
   };
   

/*!
\brief Get mag (Magnetic field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   magT& mag(void) {
      if constexpr (std::is_same<T, magT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::mag();
   };

/*!
\brief Get mag (Magnetic field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const magT& mag(void) const {
      if constexpr (std::is_same<T, magT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::mag();
   };


/*!
\brief Whether mag (Magnetic field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool mag_found(void) {
      if constexpr (std::is_same<T, magT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::mag_found();
   };
   

/*!
\brief Get fmag (Magnetic field flux function) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   fmagT& fmag(void) {
      if constexpr (std::is_same<T, fmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fmag();
   };

/*!
\brief Get fmag (Magnetic field flux function) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const fmagT& fmag(void) const {
      if constexpr (std::is_same<T, fmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fmag();
   };


/*!
\brief Whether fmag (Magnetic field flux function) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool fmag_found(void) {
      if constexpr (std::is_same<T, fmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::fmag_found();
   };
   

/*!
\brief Get glm (Lagrange multiplier field of GLM MHD) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   glmT& glm(void) {
      if constexpr (std::is_same<T, glmT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::glm();
   };

/*!
\brief Get glm (Lagrange multiplier field of GLM MHD) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const glmT& glm(void) const {
      if constexpr (std::is_same<T, glmT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::glm();
   };


/*!
\brief Whether glm (Lagrange multiplier field of GLM MHD) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool glm_found(void) {
      if constexpr (std::is_same<T, glmT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::glm_found();
   };
   

/*!
\brief Get fglm (Lagrange mutlipler flux function of GLM MHD) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   fglmT& fglm(void) {
      if constexpr (std::is_same<T, fglmT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fglm();
   };

/*!
\brief Get fglm (Lagrange mutlipler flux function of GLM MHD) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const fglmT& fglm(void) const {
      if constexpr (std::is_same<T, fglmT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::fglm();
   };


/*!
\brief Whether fglm (Lagrange mutlipler flux function of GLM MHD) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool fglm_found(void) {
      if constexpr (std::is_same<T, fglmT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::fglm_found();
   };
   

/*!
\brief Get ele (Electric field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   eleT& ele(void) {
      if constexpr (std::is_same<T, eleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::ele();
   };

/*!
\brief Get ele (Electric field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const eleT& ele(void) const {
      if constexpr (std::is_same<T, eleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::ele();
   };


/*!
\brief Whether ele (Electric field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool ele_found(void) {
      if constexpr (std::is_same<T, eleT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::ele_found();
   };
   

/*!
\brief Get Mmag (Magnetic field magnitude) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   MmagT& Mmag(void) {
      if constexpr (std::is_same<T, MmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Mmag();
   };

/*!
\brief Get Mmag (Magnetic field magnitude) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const MmagT& Mmag(void) const {
      if constexpr (std::is_same<T, MmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Mmag();
   };


/*!
\brief Whether Mmag (Magnetic field magnitude) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Mmag_found(void) {
      if constexpr (std::is_same<T, MmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Mmag_found();
   };
   

/*!
\brief Get Dmag (Magnetic field direction) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   DmagT& Dmag(void) {
      if constexpr (std::is_same<T, DmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Dmag();
   };

/*!
\brief Get Dmag (Magnetic field direction) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const DmagT& Dmag(void) const {
      if constexpr (std::is_same<T, DmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Dmag();
   };


/*!
\brief Whether Dmag (Magnetic field direction) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Dmag_found(void) {
      if constexpr (std::is_same<T, DmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Dmag_found();
   };
   

/*!
\brief Get Gvel (Gradient of velocity field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   GvelT& Gvel(void) {
      if constexpr (std::is_same<T, GvelT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gvel();
   };

/*!
\brief Get Gvel (Gradient of velocity field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const GvelT& Gvel(void) const {
      if constexpr (std::is_same<T, GvelT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gvel();
   };


/*!
\brief Whether Gvel (Gradient of velocity field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Gvel_found(void) {
      if constexpr (std::is_same<T, GvelT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Gvel_found();
   };
   

/*!
\brief Get Gele (Gradient of electric field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   GeleT& Gele(void) {
      if constexpr (std::is_same<T, GeleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gele();
   };

/*!
\brief Get Gele (Gradient of electric field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const GeleT& Gele(void) const {
      if constexpr (std::is_same<T, GeleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gele();
   };


/*!
\brief Whether Gele (Gradient of electric field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Gele_found(void) {
      if constexpr (std::is_same<T, GeleT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Gele_found();
   };
   

/*!
\brief Get Gmag (Gradient of magnetic field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   GmagT& Gmag(void) {
      if constexpr (std::is_same<T, GmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gmag();
   };

/*!
\brief Get Gmag (Gradient of magnetic field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const GmagT& Gmag(void) const {
      if constexpr (std::is_same<T, GmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Gmag();
   };


/*!
\brief Whether Gmag (Gradient of magnetic field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Gmag_found(void) {
      if constexpr (std::is_same<T, GmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Gmag_found();
   };
   

/*!
\brief Get GMmag (Gradient of magnetic field magnitude) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   GMmagT& GMmag(void) {
      if constexpr (std::is_same<T, GMmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::GMmag();
   };

/*!
\brief Get GMmag (Gradient of magnetic field magnitude) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const GMmagT& GMmag(void) const {
      if constexpr (std::is_same<T, GMmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::GMmag();
   };


/*!
\brief Whether GMmag (Gradient of magnetic field magnitude) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool GMmag_found(void) {
      if constexpr (std::is_same<T, GMmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::GMmag_found();
   };
   

/*!
\brief Get GDmag (Gradient of magnetic field direction ) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   GDmagT& GDmag(void) {
      if constexpr (std::is_same<T, GDmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::GDmag();
   };

/*!
\brief Get GDmag (Gradient of magnetic field direction ) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const GDmagT& GDmag(void) const {
      if constexpr (std::is_same<T, GDmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::GDmag();
   };


/*!
\brief Whether GDmag (Gradient of magnetic field direction ) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool GDmag_found(void) {
      if constexpr (std::is_same<T, GDmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::GDmag_found();
   };
   

/*!
\brief Get Tvel (Time derivative of velocity field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   TvelT& Tvel(void) {
      if constexpr (std::is_same<T, TvelT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tvel();
   };

/*!
\brief Get Tvel (Time derivative of velocity field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const TvelT& Tvel(void) const {
      if constexpr (std::is_same<T, TvelT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tvel();
   };


/*!
\brief Whether Tvel (Time derivative of velocity field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Tvel_found(void) {
      if constexpr (std::is_same<T, TvelT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Tvel_found();
   };
   

/*!
\brief Get Tele (Time derivative of electric field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   TeleT& Tele(void) {
      if constexpr (std::is_same<T, TeleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tele();
   };

/*!
\brief Get Tele (Time derivative of electric field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const TeleT& Tele(void) const {
      if constexpr (std::is_same<T, TeleT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tele();
   };


/*!
\brief Whether Tele (Time derivative of electric field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Tele_found(void) {
      if constexpr (std::is_same<T, TeleT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Tele_found();
   };
   

/*!
\brief Get Tmag (Time derivative of magnetic field) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   TmagT& Tmag(void) {
      if constexpr (std::is_same<T, TmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tmag();
   };

/*!
\brief Get Tmag (Time derivative of magnetic field) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const TmagT& Tmag(void) const {
      if constexpr (std::is_same<T, TmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::Tmag();
   };


/*!
\brief Whether Tmag (Time derivative of magnetic field) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool Tmag_found(void) {
      if constexpr (std::is_same<T, TmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::Tmag_found();
   };
   

/*!
\brief Get TMmag (Time derivative of magnetic field magnitude) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   TMmagT& TMmag(void) {
      if constexpr (std::is_same<T, TMmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::TMmag();
   };

/*!
\brief Get TMmag (Time derivative of magnetic field magnitude) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const TMmagT& TMmag(void) const {
      if constexpr (std::is_same<T, TMmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::TMmag();
   };


/*!
\brief Whether TMmag (Time derivative of magnetic field magnitude) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool TMmag_found(void) {
      if constexpr (std::is_same<T, TMmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::TMmag_found();
   };
   

/*!
\brief Get TDmag (Time derivative of magnetic field direction) from the data type, as lvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   TDmagT& TDmag(void) {
      if constexpr (std::is_same<T, TDmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::TDmag();
   };

/*!
\brief Get TDmag (Time derivative of magnetic field direction) from the data type, as const rvalue.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   const TDmagT& TDmag(void) const {
      if constexpr (std::is_same<T, TDmagT>::value)
         return data;
      else
         return NamedMHDtuple<nameid, Ts...>::TDmag();
   };


/*!
\brief Whether TDmag (Time derivative of magnetic field direction) is in the data type.
\author Lucius Schoenbaum
\date 3/25/2025
*/
   bool TDmag_found(void) {
      if constexpr (std::is_same<T, TDmagT>::value)
         return true;
      else
         return NamedMHDtuple<nameid, Ts...>::TDmag_found();
   };
   

   // END(variables/generate, class)


/*!
\author Lucius Schoenbaum
\date 05/28/2025
\return string representation of state, for testing purposes
*/
   std::string str(bool recursive = false) const {
      std::string out;
      if (!recursive) out += std::string(VariableNames[nameid]) + "{";
      out += data.str() + ", " + NamedMHDtuple<nameid, Ts...>::str(true);
      if (!recursive) out += "}";
      return out;
   }

};


/*!
\brief Base for NamedMHDtuple data type construction.
\author Lucius Schoenbaum
\author Vladimir Florinski
\note There is no doxygen documentation for features in this class,
as the information is only relevant to the implementation.
*/
template <VariableId nameid, typename T>
struct NamedMHDtuple<nameid, T> {

protected:

   T data;

   template <typename Function>
   void visit_unpacked(std::size_t index, Function&& f, auto&&... others) {
      if (index == 0)
         f(data, others.data...);
      else
         throw std::out_of_range("[NamedMHDtuple] out of range");
   }

   template <typename Function>
   void foreach_unpacked(Function&& f, auto&&... others) {
      f(data, others.data...);
   }

public:

   static constexpr const std::string_view name = VariableNames[nameid];

   NamedMHDtuple(void) = default;

   explicit NamedMHDtuple(T in):
       data(in)
   {};


   NamedMHDtuple& operator=(const NamedMHDtuple& other) {
      data = other.data;
      return *this;
   };

   size_t size() const {
      return 1;
   }
  
   const T& top() const {
      return data;
   }

   T& top() {
      return data;
   }

   std::any operator[](std::size_t index) const {
      if (index == 0)
         return data;
      else
         throw std::out_of_range("[NamedMHDtuple] out of range");
   }

   template <typename Function, typename Others>
   void visit(std::size_t index, Function&& f, Others&& others) {
      std::apply(
            [&](auto&&... others) {
               visit_unpacked(index, std::forward<Function>(f), std::forward<decltype(others)>(others)...);
            },
            std::forward<Others>(others)
      );
   }

   template <typename Function, typename Others>
   void foreach(Function&& f, Others&& others) {
      std::apply(
            [&](auto&&... others) {
               foreach_unpacked(std::forward<Function>(f), std::forward<decltype(others)>(others)...);
            },
            std::forward<Others>(others)
      );
   }

   template <typename Function>
   void foreach(Function&& f) {
      f(data);
   }

   // BEGIN(variables/generate, base)

   denT& den(void) {
      if constexpr (std::is_same<T, denT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] den (Fluid density field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const denT& den(void) const {
   if constexpr (std::is_same<T, denT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] den (Fluid density field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool den_found(void) {
      if constexpr (std::is_same<T, denT>::value)
         return true;
      else
         return false;
   };

   fdenT& fden(void) {
      if constexpr (std::is_same<T, fdenT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] fden (Fluid density flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const fdenT& fden(void) const {
   if constexpr (std::is_same<T, fdenT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] fden (Fluid density flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool fden_found(void) {
      if constexpr (std::is_same<T, fdenT>::value)
         return true;
      else
         return false;
   };

   prsT& prs(void) {
      if constexpr (std::is_same<T, prsT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] prs (Fluid pressure field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const prsT& prs(void) const {
   if constexpr (std::is_same<T, prsT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] prs (Fluid pressure field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool prs_found(void) {
      if constexpr (std::is_same<T, prsT>::value)
         return true;
      else
         return false;
   };

   enrT& enr(void) {
      if constexpr (std::is_same<T, enrT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] enr (Fluid energy field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const enrT& enr(void) const {
   if constexpr (std::is_same<T, enrT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] enr (Fluid energy field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool enr_found(void) {
      if constexpr (std::is_same<T, enrT>::value)
         return true;
      else
         return false;
   };

   fenrT& fenr(void) {
      if constexpr (std::is_same<T, fenrT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] fenr (Fluid energy flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const fenrT& fenr(void) const {
   if constexpr (std::is_same<T, fenrT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] fenr (Fluid energy flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool fenr_found(void) {
      if constexpr (std::is_same<T, fenrT>::value)
         return true;
      else
         return false;
   };

   velT& vel(void) {
      if constexpr (std::is_same<T, velT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] vel (Fluid velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const velT& vel(void) const {
   if constexpr (std::is_same<T, velT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] vel (Fluid velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool vel_found(void) {
      if constexpr (std::is_same<T, velT>::value)
         return true;
      else
         return false;
   };

   momT& mom(void) {
      if constexpr (std::is_same<T, momT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] mom (Fluid momentum field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const momT& mom(void) const {
   if constexpr (std::is_same<T, momT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] mom (Fluid momentum field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool mom_found(void) {
      if constexpr (std::is_same<T, momT>::value)
         return true;
      else
         return false;
   };

   fmomT& fmom(void) {
      if constexpr (std::is_same<T, fmomT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] fmom (Fluid momentum flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const fmomT& fmom(void) const {
   if constexpr (std::is_same<T, fmomT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] fmom (Fluid momentum flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool fmom_found(void) {
      if constexpr (std::is_same<T, fmomT>::value)
         return true;
      else
         return false;
   };

   magT& mag(void) {
      if constexpr (std::is_same<T, magT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] mag (Magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const magT& mag(void) const {
   if constexpr (std::is_same<T, magT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] mag (Magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool mag_found(void) {
      if constexpr (std::is_same<T, magT>::value)
         return true;
      else
         return false;
   };

   fmagT& fmag(void) {
      if constexpr (std::is_same<T, fmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] fmag (Magnetic field flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const fmagT& fmag(void) const {
   if constexpr (std::is_same<T, fmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] fmag (Magnetic field flux function) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool fmag_found(void) {
      if constexpr (std::is_same<T, fmagT>::value)
         return true;
      else
         return false;
   };

   glmT& glm(void) {
      if constexpr (std::is_same<T, glmT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] glm (Lagrange multiplier field of GLM MHD) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const glmT& glm(void) const {
   if constexpr (std::is_same<T, glmT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] glm (Lagrange multiplier field of GLM MHD) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool glm_found(void) {
      if constexpr (std::is_same<T, glmT>::value)
         return true;
      else
         return false;
   };

   fglmT& fglm(void) {
      if constexpr (std::is_same<T, fglmT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] fglm (Lagrange mutlipler flux function of GLM MHD) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const fglmT& fglm(void) const {
   if constexpr (std::is_same<T, fglmT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] fglm (Lagrange mutlipler flux function of GLM MHD) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool fglm_found(void) {
      if constexpr (std::is_same<T, fglmT>::value)
         return true;
      else
         return false;
   };

   eleT& ele(void) {
      if constexpr (std::is_same<T, eleT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] ele (Electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const eleT& ele(void) const {
   if constexpr (std::is_same<T, eleT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] ele (Electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool ele_found(void) {
      if constexpr (std::is_same<T, eleT>::value)
         return true;
      else
         return false;
   };

   MmagT& Mmag(void) {
      if constexpr (std::is_same<T, MmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Mmag (Magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const MmagT& Mmag(void) const {
   if constexpr (std::is_same<T, MmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Mmag (Magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Mmag_found(void) {
      if constexpr (std::is_same<T, MmagT>::value)
         return true;
      else
         return false;
   };

   DmagT& Dmag(void) {
      if constexpr (std::is_same<T, DmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Dmag (Magnetic field direction) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const DmagT& Dmag(void) const {
   if constexpr (std::is_same<T, DmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Dmag (Magnetic field direction) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Dmag_found(void) {
      if constexpr (std::is_same<T, DmagT>::value)
         return true;
      else
         return false;
   };

   GvelT& Gvel(void) {
      if constexpr (std::is_same<T, GvelT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Gvel (Gradient of velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const GvelT& Gvel(void) const {
   if constexpr (std::is_same<T, GvelT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Gvel (Gradient of velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Gvel_found(void) {
      if constexpr (std::is_same<T, GvelT>::value)
         return true;
      else
         return false;
   };

   GeleT& Gele(void) {
      if constexpr (std::is_same<T, GeleT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Gele (Gradient of electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const GeleT& Gele(void) const {
   if constexpr (std::is_same<T, GeleT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Gele (Gradient of electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Gele_found(void) {
      if constexpr (std::is_same<T, GeleT>::value)
         return true;
      else
         return false;
   };

   GmagT& Gmag(void) {
      if constexpr (std::is_same<T, GmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Gmag (Gradient of magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const GmagT& Gmag(void) const {
   if constexpr (std::is_same<T, GmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Gmag (Gradient of magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Gmag_found(void) {
      if constexpr (std::is_same<T, GmagT>::value)
         return true;
      else
         return false;
   };

   GMmagT& GMmag(void) {
      if constexpr (std::is_same<T, GMmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] GMmag (Gradient of magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const GMmagT& GMmag(void) const {
   if constexpr (std::is_same<T, GMmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] GMmag (Gradient of magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool GMmag_found(void) {
      if constexpr (std::is_same<T, GMmagT>::value)
         return true;
      else
         return false;
   };

   GDmagT& GDmag(void) {
      if constexpr (std::is_same<T, GDmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] GDmag (Gradient of magnetic field direction ) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const GDmagT& GDmag(void) const {
   if constexpr (std::is_same<T, GDmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] GDmag (Gradient of magnetic field direction ) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool GDmag_found(void) {
      if constexpr (std::is_same<T, GDmagT>::value)
         return true;
      else
         return false;
   };

   TvelT& Tvel(void) {
      if constexpr (std::is_same<T, TvelT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Tvel (Time derivative of velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const TvelT& Tvel(void) const {
   if constexpr (std::is_same<T, TvelT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Tvel (Time derivative of velocity field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Tvel_found(void) {
      if constexpr (std::is_same<T, TvelT>::value)
         return true;
      else
         return false;
   };

   TeleT& Tele(void) {
      if constexpr (std::is_same<T, TeleT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Tele (Time derivative of electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const TeleT& Tele(void) const {
   if constexpr (std::is_same<T, TeleT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Tele (Time derivative of electric field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Tele_found(void) {
      if constexpr (std::is_same<T, TeleT>::value)
         return true;
      else
         return false;
   };

   TmagT& Tmag(void) {
      if constexpr (std::is_same<T, TmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] Tmag (Time derivative of magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const TmagT& Tmag(void) const {
   if constexpr (std::is_same<T, TmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] Tmag (Time derivative of magnetic field) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool Tmag_found(void) {
      if constexpr (std::is_same<T, TmagT>::value)
         return true;
      else
         return false;
   };

   TMmagT& TMmag(void) {
      if constexpr (std::is_same<T, TMmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] TMmag (Time derivative of magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const TMmagT& TMmag(void) const {
   if constexpr (std::is_same<T, TMmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] TMmag (Time derivative of magnetic field magnitude) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool TMmag_found(void) {
      if constexpr (std::is_same<T, TMmagT>::value)
         return true;
      else
         return false;
   };

   TDmagT& TDmag(void) {
      if constexpr (std::is_same<T, TDmagT>::value)
         return data;
      else
        throw std::invalid_argument( "[NamedMHDtuple] TDmag (Time derivative of magnetic field direction) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
  const TDmagT& TDmag(void) const {
   if constexpr (std::is_same<T, TDmagT>::value)
      return data;
   else
      throw std::invalid_argument( "[NamedMHDtuple] TDmag (Time derivative of magnetic field direction) was not found: the tuple does not contain the requested value type. You can add this value type when you build the tuple type." );
   };
   
   bool TDmag_found(void) {
      if constexpr (std::is_same<T, TDmagT>::value)
         return true;
      else
         return false;
   };

   // END(variables/generate, base)

   std::string str(bool recursive = false) const {
      if (recursive)
         return data.str();
      else
         return std::string(VariableNames[nameid]) + "{" + data.str() + "}";
   }

};

/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] tup const NamedMHDtuple type
\return The `I`th member of tuple, for template argument integer `I`
 \note The calling pattern is the same as that of std::get.
\note The value of template argument `I` must be known at compile time,
which can constraint usage in some situations. In these cases you may be
able use class method foreach() with one of the argument signatures.
*/
template <std::size_t I, VariableId nameid, typename T, typename... Ts>
decltype(auto) get(const NamedMHDtuple<nameid, T, Ts...>& tup) {
   if constexpr (I == 0)
      return tup.top();
   else
      return get<I-1>(static_cast<const NamedMHDtuple<nameid, Ts...>&>(tup));
}

/*!
\author Lucius Schoenbaum
\date 06/02/2025
\param[in] tup NamedMHDtuple type
\return The `I`th member of tuple, for template argument integer `I`
\note The calling pattern is the same as that of std::get.
\note The value of template argument `I` must be known at compile time,
which can constraint usage in some situations. In these cases you may be
able use class method foreach() with one of the argument signatures.
*/
template <std::size_t I, VariableId nameid, typename T, typename... Ts>
decltype(auto) get(NamedMHDtuple<nameid, T, Ts...>& tup) {
   if constexpr (I == 0)
      return tup.top();
   else
      return get<I-1>(static_cast<NamedMHDtuple<nameid, Ts...>&>(tup));
}

};

#endif
