/*!
\file background.config.hh
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
* This file is automatically generated by config.py. Do not edit this file, instead edit config.py. 
*/

#ifndef SPECTRUM_BACKGROUND_CONFIG_HH
#define SPECTRUM_BACKGROUND_CONFIG_HH

#include "common/compiletime_lists.hh"
#include "common/fields.hh"

namespace Spectrum {

// forward declaration of vector type
// class GeoVector;

template<Config::Background background_, SpecieId specieid_>
struct BackgroundConfig;

/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: CylindricalObstacle
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::CylindricalObstacle, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::CylindricalObstacle;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: DataBATL
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::DataBATL, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::DataBATL;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::numeric;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: server_num_ghost_cells
// Description: number of ghost cells (server parameter)
   static constexpr int server_num_ghost_cells = 2;
//! Name: server_interpolation_order
// Description: server_interpolation_order
   static constexpr int server_interpolation_order = 1;
//! Name: servers_are_workers
// Description: Whether servers are workers. Servers only exist if the background is a data-serving background.
   static constexpr bool allow_server_worker = false;
//! Name: file_name_pattern
// Description: File name pattern used for stored data.
   static constexpr std::string_view file_name_pattern = "data";
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: DataCartesian
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::DataCartesian, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::DataCartesian;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::numeric;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: server_num_ghost_cells
// Description: number of ghost cells (server parameter)
   static constexpr int server_num_ghost_cells = 2;
//! Name: server_interpolation_order
// Description: server_interpolation_order
   static constexpr int server_interpolation_order = 1;
//! Name: servers_are_workers
// Description: Whether servers are workers. Servers only exist if the background is a data-serving background.
   static constexpr bool allow_server_worker = false;
//! Name: file_name_pattern
// Description: File name pattern used for stored data.
   static constexpr std::string_view file_name_pattern = "data";
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: Dipole
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::Dipole, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::Dipole;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: dmax_fraction
// Description: Fraction of dmax in a reduced region (background dependent)
   static constexpr double dmax_fraction = 0.1;
//! Name: r0
// Description: value (todo: description)
   static constexpr GeoVector r0 = {0.0, 0.0, 0.0};
//! Name: u0
// Description: u0
   static constexpr GeoVector u0 = {0.0, 0.0, 0.0};
//! Name: B0
// Description: B0
   static constexpr GeoVector B0 = {1.0, 1.0, 1.0};
//! Name: r_ref
// Description: Reference equatorial distance
   static constexpr double r_ref = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: Discontinuity
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::Discontinuity, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::Discontinuity;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: MagnetizedCylinder
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::MagnetizedCylinder, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::MagnetizedCylinder;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: MagnetizedSphere
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::MagnetizedSphere, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::MagnetizedSphere;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: Shock
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::Shock, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::Shock;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: tanh_width_factor
// Description: Scaling factor to better match discontinuity width when using smooth discontinuity (tanh)
   static constexpr double tanh_width_factor = 4.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: SmoothDiscontinuity
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::SmoothDiscontinuity, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::SmoothDiscontinuity;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: smooth_discontinuity_order
// Description: Parameter controlling smoothness of discontinuity/shock
// Options: 0: not continuous | 1: differentiable | 2: twice differentiable | 3: thrice differentiable | 4, 5, >5: smooth
   static constexpr int smooth_discontinuity_order = 4;
//! Name: tanh_width_factor
// Description: Scaling factor to better match discontinuity width when using smooth discontinuity (tanh)
   static constexpr double tanh_width_factor = 4.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: SmoothShock
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::SmoothShock, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::SmoothShock;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: smooth_discontinuity_order
// Description: Parameter controlling smoothness of discontinuity/shock
// Options: 0: not continuous | 1: differentiable | 2: twice differentiable | 3: thrice differentiable | 4, 5, >5: smooth
   static constexpr int smooth_discontinuity_order = 4;
//! Name: tanh_width_factor
// Description: Scaling factor to better match discontinuity width when using smooth discontinuity (tanh)
   static constexpr double tanh_width_factor = 4.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: SolarWind
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::SolarWind, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::SolarWind;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::numeric;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: solarwind_current_sheet
// Description: Heliospheric current sheet
// Options: disabled | flat | wavy_static: wavy (Jokipii-Thomas 1981) and static | wavy_time_dependent: wavy and time-dependent
   static constexpr auto solarwind_current_sheet = BackgroundOptions::CurrentSheet::disabled;
//! Name: solarwind_sectored_region
// Description: Magnetic topology region
// Options: nowhere | HCS
   static constexpr auto solarwind_sectored_region = BackgroundOptions::SectoredRegion::nowhere;
//! Name: solarwind_polar_correction
// Description: Correction to Parker Spiral, mainly for polar regions
// Options: none | Smith_Bieber: Smith-Bieber 1991 | Zurbuchen_etal: Zurbuchen et al. 1997 | Schwadron_McComas: Schwadron-McComas 2003
   static constexpr auto solarwind_polar_correction = BackgroundOptions::PolarCorrection::none;
//! Name: solarwind_speed_latitude_profile
// Description: Latitudinal profile for bulk speed
// Options: constant | linear_step | smooth_step
   static constexpr auto solarwind_speed_latitude_profile = BackgroundOptions::SpeedLatitudeProfile::constant;
//! Name: with_termination_shock
// Description: Whether the model has a spherical termination shock feature (requires extra setup, see source/documentation)
   static constexpr bool with_termination_shock = false;
//! Name: termshock_speed_exponent
// Description: Integer exponent of decrease of solar wind speed beyond the termination shock
// Options: zero | one | square | cube
   static constexpr auto termshock_speed_exponent = BackgroundOptions::TermShockSpeedExponent::square;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: SphericalObstacle
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::SphericalObstacle, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::SphericalObstacle;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: r_ref
// Description: Reference equatorial distance
   static constexpr double r_ref = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: Uniform
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::Uniform, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::Uniform;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: VLISMBochum
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::VLISMBochum, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::VLISMBochum;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::numeric;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
//! Name: mod_type
// Description: What function to use within 'get_ampfactor'
// Options: none | zero | constant | scaled
   static constexpr auto mod_type = BackgroundOptions::ModType::scaled;
//! Name: mod_rpos
// Description: Whether to scale relative to s=0 or s=+inf
// Options: scale_rel_zero | scale_rel_inf
   static constexpr auto mod_rpos = BackgroundOptions::ModRPos::scale_rel_zero;
//! Name: z_nose
// Description: todo
   static constexpr double z_nose = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Background class
\author Lucius Schoenbaum
\date 09/29/2025
Background: Waves
*/
template<SpecieId specieid_>
struct BackgroundConfig<Config::Background::Waves, specieid_> {
//! Name: background
// Description: The background type used for simulation
// Options: CylindricalObstacle | DataBATL | DataCartesian | Dipole | Discontinuity | MagnetizedCylinder | MagnetizedSphere | Shock | SmoothDiscontinuity | SmoothShock | SolarWind | SphericalObstacle | Uniform | VLISMBochum | Waves
   static constexpr auto background = Config::Background::Waves;
//! Name: derivative_method
// Description: The method used to evaluate derivatives of spatially located field quantities. Usually, the only information checked is whether or not this value is numeric.
// Options: numeric | nonnumeric | analytic | datadefined
   static constexpr auto derivative_method = BackgroundOptions::DerivativeMethod::analytic;
//! Name: num_numeric_grad_evals
// Description: The number of derivative evaluations applied in the derivative-averaging method
   static constexpr int num_numeric_grad_evals = 1;
//! Name: incr_dmax_ratio
// Description: What fraction of _dmax to use to calculate the field increment
   static constexpr double incr_dmax_ratio = 0.0001;
//! Name: dmax0
// Description: baseline simulation-wide dmax value
   static constexpr double dmax0 = 0.1;
};



}

#endif

