/*!
\file diffusion.config.hh
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
* This file is automatically generated by config.py. Do not edit this file, instead edit config.py. 
*/

#ifndef SPECTRUM_DIFFUSION_CONFIG_HH
#define SPECTRUM_DIFFUSION_CONFIG_HH

#include "common/compiletime_lists.hh"
#include "common/fields.hh"

namespace Spectrum {

// forward declaration of vector type
// class GeoVector;

template<Config::Diffusion diffusion_, SpecieId specieid_>
struct DiffusionConfig;

/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: None
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::None, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::None;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<>>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>>;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: IsotropicConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::IsotropicConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::IsotropicConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: D0
// Description: diffusion coefficient (if constant)
   static constexpr double D0 = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: QLTConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::QLTConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::QLTConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: A2A
// Description: Alfven turbulence relative variance
   static constexpr double A2A = 1.0;
//! Name: l_max
// Description: Maximum turbulent lengthscale
   static constexpr double l_max = 1.0;
//! Name: ps_index
// Description: Power spectral index
   static constexpr double ps_index = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: WNLTConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::WNLTConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::WNLTConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
   static constexpr bool use_qlt_scatt = false;
//! Name: A2A
// Description: Alfven turbulence relative variance
   static constexpr double A2A = 1.0;
//! Name: l_max
// Description: Maximum turbulent lengthscale
   static constexpr double l_max = 1.0;
//! Name: ps_index
// Description: Power spectral index
   static constexpr double ps_index = 1.0;
//! Name: A2T
// Description: Transverse turbulence relative variance
   static constexpr double A2T = 1.0;
//! Name: A2L
// Description: Longitudinal turbulence relative variance
   static constexpr double A2L = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: WNLTRampVLISM
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::WNLTRampVLISM, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::WNLTRampVLISM;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
   static constexpr bool use_qlt_scatt = false;
//! Name: A2A_ref
// Description: Reference Alfven turbulence relative variance
   static constexpr double A2A_ref = 1.0;
//! Name: l_max_ref
// Description: Reference maximum turbulent lengthscale
   static constexpr double l_max_ref = 1.0;
//! Name: ps_index
// Description: Power spectral index
   static constexpr double ps_index = 1.0;
//! Name: A2T_ref
// Description: Reference transverse turbulence relative variance
   static constexpr double A2T_ref = 1.0;
//! Name: A2L_ref
// Description: Reference longitudinal turbulence relative variance
   static constexpr double A2L_ref = 1.0;
//! Name: l_max_HP
// Description: Largest scale of turbulence at HP (Heliopause)
   static constexpr double l_max_HP = 1.0;
//! Name: dl_max
// Description: Difference between largest scales
   static constexpr double dl_max = 1.0;
//! Name: z_nose
// Description: Extent of the HP in the nose direction
   static constexpr double z_nose = 1.0;
//! Name: z_sheath
// Description: Extent of the sheath in the nose direction
   static constexpr double z_sheath = 1.0;
//! Name: nose_dz
// Description: Difference between nose distance
   static constexpr double nose_dz = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: ParaConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::ParaConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::ParaConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: D0
// Description: diffusion coefficient (if constant)
   static constexpr double D0 = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: PerpConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::PerpConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::PerpConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: D0
// Description: diffusion coefficient (if constant)
   static constexpr double D0 = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: FullConstant
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::FullConstant, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::FullConstant;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: Dperp
// Description: diffusion coefficient (if constant)
   static constexpr double Dperp = 1.0;
//! Name: Dpara
// Description: diffusion coefficient (if constant)
   static constexpr double Dpara = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: FlowMomentumPowerLaw
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::FlowMomentumPowerLaw, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::FlowMomentumPowerLaw;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t, Fluv_t, AbsFluv_t, DotFluv_t, DelFluv_t>;
//! Name: kappa0
// Description: Reference diffusion coefficient
   static constexpr double kappa0 = 1.0;
//! Name: U0
// Description: Flow velocity normalization factor
   static constexpr double U0 = 1.0;
//! Name: pow_law_U
// Description: Power law slope for flow velocity
   static constexpr double pow_law_U = 1.0;
//! Name: p0
// Description: Momentum normalization factor
   static constexpr double p0 = 1.0;
//! Name: pow_law_p
// Description: Power law slope for momentum
   static constexpr double pow_law_p = 1.0;
//! Name: kappa_ratio
// Description: Ratio of perpendicular to parallel diffusion
   static constexpr double kappa_ratio = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: KineticEnergyRadialDistancePowerLaw
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::KineticEnergyRadialDistancePowerLaw, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::KineticEnergyRadialDistancePowerLaw;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: kappa0
// Description: Reference diffusion coefficient
   static constexpr double kappa0 = 1.0;
//! Name: T0
// Description: Kinetic Energy normalization factor
   static constexpr double T0 = 1.0;
//! Name: r0
// Description: Radial distance normalization factor
   static constexpr double r0 = 1.0;
//! Name: pow_law_T
// Description: Power law slope for kinetic energy
   static constexpr double pow_law_T = 1.0;
//! Name: pow_law_r
// Description: Power law slope for radial distance
   static constexpr double pow_law_r = 1.0;
//! Name: kappa_ratio
// Description: Ratio of perpendicular to parallel diffusion
   static constexpr double kappa_ratio = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: RigidityMagneticFieldPowerLaw
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::RigidityMagneticFieldPowerLaw, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::RigidityMagneticFieldPowerLaw;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: lam0
// Description: Parallel mean free path
   static constexpr double lam0 = 1.0;
//! Name: R0
// Description: Rigidity normalization factor
   static constexpr double R0 = 1.0;
//! Name: B0
// Description: Magnetic field normalization factor
   static constexpr double B0 = 1.0;
//! Name: pow_law_R
// Description: Power law slope for rigidity
   static constexpr double pow_law_R = 1.0;
//! Name: pow_law_B
// Description: Power law slope for magnetic field
   static constexpr double pow_law_B = 1.0;
//! Name: kappa_ratio
// Description: Ratio of perpendicular to parallel diffusion
   static constexpr double kappa_ratio = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: StraussEtAl2013
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::StraussEtAl2013, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::StraussEtAl2013;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: LISM_idx
// Description: Index for LISM indicator variable
   static constexpr int LISM_idx = 1;
//! Name: lam_inner
// Description: Parallel inner heliosphere mean free path
   static constexpr double lam_inner = 1.0;
//! Name: lam_outer
// Description: Parallel outer heliosphere mean free path
   static constexpr double lam_outer = 1.0;
//! Name: R0
// Description: Rigidity normalization factor
   static constexpr double R0 = 1.0;
//! Name: B0
// Description: Magnetic field normalization factor
   static constexpr double B0 = 1.0;
//! Name: kappa_ratio_inner
// Description: Ratio of perpendicular to parallel diffusion inner heliosphere
   static constexpr double kappa_ratio_inner = 1.0;
//! Name: kappa_ratio_outer
// Description: Ratio of perpendicular to parallel diffusion outer heliosphere
   static constexpr double kappa_ratio_outer = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: GuoEtAl2014
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::GuoEtAl2014, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::GuoEtAl2014;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: LISM_idx
// Description: Index for LISM indicator variable
   static constexpr int LISM_idx = 1;
//! Name: lam_inner
// Description: Parallel inner heliosphere mean free path
   static constexpr double lam_inner = 1.0;
//! Name: lam_outer
// Description: Parallel outer heliosphere mean free path
   static constexpr double lam_outer = 1.0;
//! Name: R0
// Description: Rigidity normalization factor
   static constexpr double R0 = 1.0;
//! Name: B0
// Description: Magnetic field normalization factor
   static constexpr double B0 = 1.0;
//! Name: kappa_ratio_inner
// Description: Ratio of perpendicular to parallel diffusion inner heliosphere
   static constexpr double kappa_ratio_inner = 1.0;
//! Name: kappa_ratio_outer
// Description: Ratio of perpendicular to parallel diffusion outer heliosphere
   static constexpr double kappa_ratio_outer = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: PotgieterEtAl2015
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::PotgieterEtAl2015, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::PotgieterEtAl2015;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: LISM_idx
// Description: Index for LISM indicator variable
   static constexpr int LISM_idx = 1;
//! Name: kappa_inner
// Description: Parallel inner heliosphere diffusion coefficient
   static constexpr double kappa_inner = 1.0;
//! Name: kappa_outer
// Description: Parallel outer heliosphere diffusion coefficient
   static constexpr double kappa_outer = 1.0;
//! Name: R0
// Description: Rigidity normalization factor
   static constexpr double R0 = 1.0;
//! Name: B0
// Description: Magnetic field normalization factor
   static constexpr double B0 = 1.0;
//! Name: kappa_ratio_inner
// Description: Ratio of perpendicular to parallel diffusion inner heliosphere
   static constexpr double kappa_ratio_inner = 1.0;
//! Name: kappa_ratio_outer
// Description: Ratio of perpendicular to parallel diffusion outer heliosphere
   static constexpr double kappa_ratio_outer = 1.0;
};


/*!
\brief (Hyper)parameters and config(uration) options for a SPECTRUM Diffusion class
\author Lucius Schoenbaum
\date 09/29/2025
Diffusion: EmpiricalSOQLTandUNLT
*/
template<SpecieId specieid_>
struct DiffusionConfig<Config::Diffusion::EmpiricalSOQLTandUNLT, specieid_> {
//! Name: diffusion
// Description: The diffusion type used for simulation
// Options: None | IsotropicConstant | QLTConstant | WNLTConstant | WNLTRampVLISM | ParaConstant | PerpConstant | FullConstant | FlowMomentumPowerLaw | KineticEnergyRadialDistancePowerLaw | RigidityMagneticFieldPowerLaw | StraussEtAl2013 | GuoEtAl2014 | PotgieterEtAl2015 | EmpiricalSOQLTandUNLT
   static constexpr auto diffusion = Config::Diffusion::EmpiricalSOQLTandUNLT;
//! Name: Coordinates
// Description: The coordinates where the diffusion is computed during the simulation.
   using Coordinates = Fields<FConfig<specieid_, CoordinateSystem::cartesian, CoordinateSystem::pitchangle>, Pos_t, Time_t, Rad_t, AbsVel_t, Mom_t>;
//! Name: Fields
// Description: The fields computed in the local environment for the diffusion computation during the simulation.
   using Fields = Fields<FConfig<>, Mag_t, AbsMag_t, DelMag_t, DelAbsMag_t, DotMag_t, DotAbsMag_t>;
//! Name: lam_para
// Description: Parallel mean free path
   static constexpr double lam_para = 1.0;
//! Name: lam_perp
// Description: Perpendicular mean free path mean free path
   static constexpr double lam_perp = 1.0;
//! Name: R0
// Description: Rigidity normalization factor
   static constexpr double R0 = 1.0;
//! Name: B0
// Description: Magnetic field normalization factor
   static constexpr double B0 = 1.0;
//! Name: Bmix_idx
// Description: Index for magnetic mixing indicator variable
   static constexpr int Bmix_idx = 1;
//! Name: kappa_ratio_red
// Description: Reduction factor for kappa in unipolar regions
   static constexpr double kappa_ratio_red = 1.0;
//! Name: radial_limit_perp_red
// Description: Radial limit to apply unipolar reduction factor
   static constexpr double radial_limit_perp_red = 1.0;
//! Name: solar_cycle_idx
// Description: Index for solar cycle indicator variable
   static constexpr int solar_cycle_idx = 1;
//! Name: solar_cycle_effect
// Description: Solar cycle effect constant
   static constexpr double solar_cycle_effect = 1.0;
};



}

#endif

