/*!
\file diffusion.config.default.hh
\brief (Hyper)parameters and config(uration) options for a SPECTRUM diffusion class
\author Lucius Schoenbaum

This file is part of the SPECTRUM suite of scientific numerical simulation codes. SPECTRUM stands for Space Plasma and Energetic Charged particle TRansport on Unstructured Meshes. The code simulates plasma or neutral particle flows using MHD equations on a grid, transport of cosmic rays using stochastic or grid based methods. The "unstructured" part refers to the use of a geodesic mesh providing a uniform coverage of the surface of a sphere.
*/

/*
 * This file is automatically generated by config.py. Do not edit this file, instead edit config.py. 
 */
 
#ifndef SPECTRUM_DIFFUSION_CONFIG_DEFAULT_HH
#define SPECTRUM_DIFFUSION_CONFIG_DEFAULT_HH

#include "diffusion.config.hh"

namespace Spectrum {

template <typename HConfig>
class DiffusionNone;
template <typename HConfig>
class DiffusionIsotropicConstant;
template <typename HConfig>
class DiffusionQLTConstant;
template <typename HConfig>
class DiffusionWNLTConstant;
template <typename HConfig>
class DiffusionWNLTRampVLISM;
template <typename HConfig>
class DiffusionParaConstant;
template <typename HConfig>
class DiffusionPerpConstant;
template <typename HConfig>
class DiffusionFullConstant;
template <typename HConfig>
class DiffusionFlowMomentumPowerLaw;
template <typename HConfig>
class DiffusionKineticEnergyRadialDistancePowerLaw;
template <typename HConfig>
class DiffusionRigidityMagneticFieldPowerLaw;
template <typename HConfig>
class DiffusionStraussEtAl2013;
template <typename HConfig>
class DiffusionGuoEtAl2014;
template <typename HConfig>
class DiffusionPotgieterEtAl2015;
template <typename HConfig>
class DiffusionEmpiricalSOQLTandUNLT;

template <typename Diffusion>
class DiffusionDefault;


template <typename HConfig>
class DiffusionDefault<DiffusionNone<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionIsotropicConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1234,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionQLTConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionWNLTConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionWNLTRampVLISM<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionParaConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1234,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionPerpConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1234,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionFullConstant<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionFlowMomentumPowerLaw<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionKineticEnergyRadialDistancePowerLaw<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionRigidityMagneticFieldPowerLaw<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionStraussEtAl2013<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionGuoEtAl2014<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionPotgieterEtAl2015<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>
   >;
};


template <typename HConfig>
class DiffusionDefault<DiffusionEmpiricalSOQLTandUNLT<HConfig>> {
   using type = DiffusionConfig<
                HConfig::specieid,
//! Name: use_qlt_scatt
// Description: Whether to use QLT pitch angle scattering with WLNT perpendicular diffusion
// Default: False
    false,
//! Name: D0
// Description: diffusion coefficient (if constant)
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dperp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: Dpara
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2A
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: k_min
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_index
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_minus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: A2L
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: ps_plus
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: l_max_HP
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: dl_max
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_nose
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_sheath
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: nose_z_dz
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: U0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: p0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: T0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: r0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: R0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: B0
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: pow_law_U
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_p
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_T
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_r
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_R
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: pow_law_B
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: LISM_idx
// Description: todo_add_description
// Default: 1
    1,
//! Name: LISM_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_ratio_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_inner
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: kappa_outer
// Description: todo_add_description
// Default: 1.0
    std::ratio<1,1>,
//! Name: lam_para
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: lam_perp
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: kappa_ratio_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: radial_limit_perp_red
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: solar_cycle_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: solar_cycle_effect
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>,
//! Name: Bmix_idx
// Description: todo_add_description
// Default: 1
    1234,
//! Name: Bmix_ind
// Description: todo_add_description
// Default: 1.0
    std::ratio<1234,1>
   >;
};



}

#endif

